a = int(input("Enter your value of a: ") )
b = int(input("Enter your value of b: ") )
print("Adding a and b")
print(a+b)
print("Subtract a and b")
print(a-b)
print("Multiply a and b")
print(a*b)
print("Divide a and b")
print(a/b)
print("Remainder left after dividing a and b")
print(a%b)